language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  - name: EmbeddingIntentClassifier
    dimensions:
     - number

policies:
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: MappingPolicy
  - name: FormPolicy
